#!/bin/bash

qemu-system-x86_64 \
    -M q35 \
    -m 256M \
    -drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2/x64/OVMF_CODE.4m.fd \
    -drive if=pflash,format=raw,file=/tmp/myos-vars.fd \
    -cdrom serega.iso
